schemas: {  }
_core:
  default_config_hash: 1uFogeFphl0Hg6oVCacZZ8mM_0wMZ7PS_RrmLbK5tf0
features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://2018-09/240_F_176078182_d7iiymhIVR3Bxy1RKjI2Fm74bLsm8dwb.jpg'
favicon:
  use_default: 1
